import lib.core.evaluationScripts as evalScript
import lib.core.file_manipulation as file_manip

_PROJECT_FOLDER = file_manip.normPath(file_manip.realPath(__file__) + '/../../../')

ICON_CLOSE_PATH = _PROJECT_FOLDER + '/icon/exit_app_48x48.png'
ICON_NAVIGATE_PATH = _PROJECT_FOLDER + '/icon/optionNavigate_128x128.png'

STR_STORAGE_DEFAULT_PATH = file_manip.normPath(file_manip.PATH_DOCUMENTS + '/PocketGIS')
STR_START_YEAR_DEFAULT, STR_START_MONTH_DEFAULT, STR_START_DAY_DEFAULT = file_manip.get_N_DaysBefore(n_days=7)
STR_END_YEAR_DEFAULT, STR_END_MONTH_DEFAULT, STR_END_DAY_DEFAULT = file_manip.getToday()

INT_START_YEAR_DEFAULT = int(STR_START_YEAR_DEFAULT)
INT_START_MONTH_DEFAULT = int(STR_START_MONTH_DEFAULT)
INT_START_DAY_DEFAULT = int(STR_START_DAY_DEFAULT)

INT_END_YEAR_DEFAULT = int(STR_END_YEAR_DEFAULT)
INT_END_MONTH_DEFAULT = int(STR_END_MONTH_DEFAULT)
INT_END_DAY_DEFAULT = int(STR_END_DAY_DEFAULT)

INT_CHUNK_SIZE_DEFAULT = 1

FLOAT_RESOLUTION_DEFAULT = 10.0

FLOAT_MIN_LATITUDE_DEFAULT = 37.5
FLOAT_MIN_LONGITUDE_DEFAULT = 23.2
FLOAT_MAX_LATITUDE_DEFAULT = 38.5
FLOAT_MAX_LONGITUDE_DEFAULT = 24.2

DICT_SATELLITE = {
    evalScript.S02_L1C_STAMP: evalScript.S02_L1C_BAND_LIST,
    evalScript.S05P_STAMP: evalScript.S05_BAND_LIST,
    evalScript.LAN08OLIL1_STAMP: evalScript.LAN08_OLI_L1_BAND_LIST
}

INT_MAX_STRETCH = 100000  # Spacer Max Stretch
